### ISSUE TITLE
`activity-watch-mode` conflicts with `recover-this-file`

### ISSUE THREAD

**Issue by benthamite** [pauldub/activity-watch-mode#23] opened 2023-07-19 13:24 UTC
Thanks for creating this package. This is to let you know that if `activity-watch` is enabled, `recover-this-file` will fail with the message “process-file: Invalid coding system: auto-save-coding”. I have experienced this issue, and [here](https://emacs.stackexchange.com/questions/14950/invalid-coding-system-auto-save-coding-when-trying-to-recover-auto-save-files#comment124363_17997) another user reports experiencing it, too.

**Comment by meliache** [comment] 2023-07-24 17:25
The Wakatime-Issue for this problem (which I got from the Stackoverflow like above) is
https://github.com/wakatime/wakatime-mode/issues/10, so ideally this should be fixed upstream in Wakatime and then merged here.

**Comment by pauldub** [comment] 2023-07-31 08:07
The wakatime issue has been open for a long time and there is a significant drift between the two projects so I think we can look for a fix ourselves and proposes changes upstream if it makes sense.

I don't have the bandwidth to look into this at the moment, but if I will happily review pull requests.

**Comment by meliache** [comment] 2024-02-12 16:22
The wakatime issue linked above has been fixed in
https://github.com/wakatime/wakatime-mode/commit/aa04a5551e782992ddaea890d8547863b0d6ba60. Explanation of the problem is in https://github.com/wakatime/wakatime-mode/issues/10#issuecomment-1905607164. I adapted the fix almost one to one in https://github.com/meliache/activity-watch-mode/commit/d5cc52dc825a39f375516eb3dabd512000b382ce, which should work if the error happens in `activity-watch--call`.

The only problem is that I haven't tested yet whether this fix works. Using my branch I didn't get any errors when running `recover-this-file`, but neither did I when I tested it with the original branch, weird :thinking: .

**Comment by benthamite** [comment] 2024-02-12 16:41
Thanks, @meliache. I have now installed your branch and will let you know if I experience any issues.

**Comment by meliache** [comment] 2024-02-19 13:05
@benthamite If it works for you I can open a PR. I just didn't do so because I don't really understand the [explanation](https://github.com/wakatime/wakatime-mode/issues/10#issuecomment-1905607164) of the issue, i.e. where exactly the coding system is evaluated in wakatime/activity-watch, and thus I was not sure about the best place where to put the fix. I just blindly copied the fix from wakatime without fully understanding it, but it seems to work for me so far. Just waiting for somebody else to test it.

**Comment by benthamite** [comment] 2024-02-19 13:20
Hi @meliache,

I haven’t noticed any issues since re-enabling the package. Just a minute ago, I deliberately force-closed a buffer so that I could later recover the file it was visiting, and running `recover-this-file` went smoothly. So it seems to be fixed.

**Closed as completed** 2024-02-19 13:59 UTC
